name: Annotate PR with trunk issues

on:
  workflow_run:
    workflows: [Pull Request]
    types: [completed]

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Annotate
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          arguments: --github-label=test
          post-annotations: true # only for fork PRs

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
          arguments: --filter=eslint --github-label=eslint          
          post-annotations: true # only for fork PRs